### ISSUE TITLE
Authorization has been denied for this request.

### ISSUE THREAD

**Issue by gabrieltrita** [pagarme/pagarme-core-api-php#11]
Alterei a versao para a v5 e tive que começar a utilizar essa biblioteca. Estou recebendo o seguinte erro ao tentar criar uma order: Authorization has been denied for this request.

Eu estou seguindo o docs atual da aplicacao para fazer a autenticação.:
new PagarmeCoreApiClient($username, $password);
A duvida é que eu vi em alguns lugares, que deveria passar a $key e a senha em branco. Qual seria o correto? É por isso que esta me dando erro?

Obrigado

**Comment by zerossB** [comment]
Mano, muito obrigado! 

Fiquei batendo a cabeça com isso faz uns 3 dias. Me ajudou bastante!
