### ISSUE TITLE
Authorization has been denied for this request.

### ISSUE THREAD

**Issue by peuweb** [pagarme/pagarme-core-api-php#48]
Verifiquei somente agora que a assinatura do método foi atualizada.

antes:
```php
new PagarmeCoreApiClient($basicAuthUserName = null, $basicAuthPassword = null);
```

depois:
```php
new PagarmeCoreApiClient($serviceRefererName = null, $basicAuthUserName = null, $basicAuthPassword = null);
```

Só não ficou muito claro que tipo de padrão devemos informar na variável `$serviceRefererName`.

Acredito ser um controle de qual aplicação as chamadas estão sendo realizadas já que esse valor também é passado no header do request da API.

Por hora estou passando o nome da minha aplicação em formato slug. Podemos considerar esse valor?

Exemplo:
```php
new PagarmeCoreApiClient('my-php-application', 'my-secret-key');
```

**Comment by prhost** [comment]
Adicionam um paramentro opcional como primeira posição do método quebrando compatibilidade e lançar em uma versão de patch 5.7.X?

Semantic version chora no chuveiro.

**Comment by peuweb** [comment]
@prhost os caras voltaram como era antes.

Aí não tem como confiar que o versionamento é feito a nível de patch.
`~5.8` esquece...

**Comment by magnomoreira** [comment]
Bom dia @peuweb , tudo bem ?
O problema foi resolvido, retiramos o parâmetro da primeira posição que estava ocasionando o 401!
correção feita na versão ~5.8.5!
Desde já peço desculpas pelo o inconveniente !
